# Generated by Django 3.0.1 on 2019-12-29 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note',
            new_name='saved_note',
        ),
    ]
